/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#171d1c",
        "on-tertiary-fixed": "#370e00",
        "inverse-surface": "#2c3130",
        "tertiary-fixed": "#ffdbce",
        "surface-tint": "#006a61",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3d4947",
        "tertiary-fixed-dim": "#ffb59a",
        "on-tertiary-fixed-variant": "#773215",
        "on-secondary": "#ffffff",
        "background": "#f5faf8",
        "tertiary-container": "#b05e3d",
        "on-secondary-fixed": "#001a42",
        "primary": "#00685f",
        "on-background": "#171d1c",
        "error-container": "#ffdad6",
        "surface-bright": "#f5faf8",
        "primary-fixed-dim": "#6bd8cb",
        "outline": "#6d7a77",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#89f5e7",
        "outline-variant": "#bcc9c6",
        "surface-container-high": "#e4e9e7",
        "on-secondary-fixed-variant": "#004395",
        "on-primary-fixed": "#00201d",
        "surface-container": "#eaefed",
        "primary-container": "#008378",
        "surface-dim": "#d6dbd9",
        "secondary-fixed-dim": "#adc6ff",
        "on-primary-container": "#f4fffc",
        "error": "#ba1a1a",
        "inverse-on-surface": "#edf2f0",
        "surface-variant": "#dee4e1",
        "surface-container-highest": "#dee4e1",
        "on-error": "#ffffff",
        "surface": "#f5faf8",
        "inverse-primary": "#6bd8cb",
        "secondary-container": "#2170e4",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#924628",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed-variant": "#005049",
        "surface-container-low": "#f0f5f2",
        "secondary": "#0058be",
        "on-secondary-container": "#fefcff",
        "secondary-fixed-variant": "#004395",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "container-max-width": "1280px",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-sm": ["14px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
